POST http://localhost:8080/register 
Content-Type: application/json

{
    "name": "John Doe",
    "email": "jhon@gmail.com",
    "password": "123456"
}

###
GET http://localhost:8000/get/dict


###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "jhon@gmail.com",
    "password": "123456"
}

###
GET http:localhost:8080/getUsersFromDB
Content-Type: application/json

###
POST http://localhost:8000/register
Content-Type: application/json

{
    "name": "Obyy",
    "email": "obyy@gmail.com",
    "password": "obyy1234"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "zeta@gmail.com",
    "password": "123456"
}

###
POST http://localhost:8000/post/level
Content-Type: application/json

{
    "userId": "Etf11PosiitbvfhH",
    "level": 6
}

###
POST http://localhost:8000/get/level
Content-Type: application/json

{
    "userId": "Etf11PosiitbvfhH"
}


###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "ollie@gmail.com",
    "password": "123456"
}

###
GET http://localhost:8000/get/quiz
Content-Type: application/json

###
POST http://localhost:8000/get/profile
Content-Type: application/json

{
    "userId": "fkFcXxPKQhgnp_TB"
}

###
POST http://localhost:8000/post/profile
Content-Type: application/json

{
    "userId": "fkFcXxPKQhgnp_TB",
    "gender": 0,
    "bday": "2003-02-07",
    "phone": "081345990819"
}